name: Build LaTeX Docs

on:
  push:
    paths:
      - 'docs/**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
          cd docs
          pdflatex main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/main.pdf
